<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-N7K85DJ" name="AUW_Test_case_prod.Practices_AgentsBrokers" tests="2" failures="0" timestamp="22 Dec 2021 09:39:17 GMT" time="122.529" errors="1">
  <testcase name="Practices_AgentsBrokers" time="68.172" classname="AUW_Test_case_prod.Practices_AgentsBrokers"/>
  <testcase name="Practices_AgentsBrokers" time="54.357" classname="AUW_Test_case_prod.Practices_AgentsBrokers">
    <error type="java.lang.AssertionError" message="expected [https://moretolove.auw.com/what-we-offer/construction-p-e] but found [about:blank]">
      <![CDATA[java.lang.AssertionError: expected [https://moretolove.auw.com/what-we-offer/construction-p-e] but found [about:blank]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at AUW_Pages.Practices_ForagentsAndBrokers.Column3_Heading(Practices_ForagentsAndBrokers.java:152)
	at AUW_Test_case_prod.Practices_AgentsBrokers.Practices_AgentsBrokers(Practices_AgentsBrokers.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </error>
  </testcase> <!-- Practices_AgentsBrokers -->
</testsuite> <!-- AUW_Test_case_prod.Practices_AgentsBrokers -->
