<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-N7K85DJ" name="AUW_Test_Case_dev.AUW_Experience" tests="2" failures="0" timestamp="14 Feb 2022 11:13:18 GMT" time="676.486" errors="1">
  <testcase name="main" time="338.428" classname="AUW_Test_Case_dev.AUW_Experience">
    <error type="java.lang.AssertionError" message="Failure message expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failure message expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at AUW_Pages.Experience_page.Exp_card1(Experience_page.java:175)
	at AUW_Test_Case_dev.AUW_Experience.main(AUW_Experience.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- main -->
  <testcase name="main" time="338.058" classname="AUW_Test_Case_dev.AUW_Experience"/>
</testsuite> <!-- AUW_Test_Case_dev.AUW_Experience -->
